# Generated by Django 4.0.4 on 2023-07-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='наименование')),
                ('category_description', models.CharField(max_length=100, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'наименование',
                'verbose_name_plural': 'наименования',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='наименование')),
                ('product_description', models.CharField(max_length=100, verbose_name='описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='preview/', verbose_name='превью')),
                ('product_prise', models.IntegerField(default=0, verbose_name='наименование')),
                ('product_date', models.DateTimeField(auto_now_add=True)),
                ('product_last', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'наименование',
                'verbose_name_plural': 'наименования',
                'ordering': ('product_name',),
            },
        ),
    ]
