# Generated by Django 4.0.4 on 2023-07-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',), 'verbose_name': 'Наименование', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_name',), 'verbose_name': 'категории', 'verbose_name_plural': 'наименования'},
        ),
    ]
