# Generated by Django 4.0.4 on 2023-07-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_product_prise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_prise',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
