# Generated by Django 4.0.4 on 2023-08-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='ссылка')),
                ('content', models.TextField(max_length=500, verbose_name='текст')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='превью')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
                ('publications', models.BooleanField(default=True, verbose_name='публикации')),
                ('views', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'заголовок',
                'verbose_name_plural': 'заголовки',
                'ordering': ('header',),
            },
        ),
    ]
