# Generated by Django 4.0.4 on 2023-07-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogging',
            options={'ordering': ('header',), 'verbose_name': 'заголовок', 'verbose_name_plural': 'заголовки'},
        ),
    ]
