# Generated by Django 4.0.4 on 2023-07-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_alter_blogging_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogging',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='ссылка'),
        ),
    ]
