# Generated by Django 4.0.4 on 2023-07-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_alter_blogging_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogging',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='blog_img/', verbose_name='превью'),
        ),
    ]
